# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position Controllers ---------------------------------------
pan_position_controller:
  type: effort_controllers/JointPositionController
  joint: pan_joint
  pid: {p: 150.0, i: 0.0, d: 0.0}
tilt_position_controller:
  type: effort_controllers/JointPositionController
  joint: tilt_joint
  pid: {p: 150.0, i: 0.0, d: 0.0}
